### PR TITLE
1.0.4 Version, Resource Pack and more Features.

### PR DESCRIPTION
**Pull request by NycuRO**
1.0.4 Version, Resource Pack and more Features.

Can anyone help me for fix conflicts?

### CODE REVIEW

**Comment by NycuRO** [comment]
@caspervanneck or @IrishPacks can help me for fix conflicts?

**Comment by caspervanneck** [comment]
yes @NycuRO

**Comment by caspervanneck** [comment]
@NycuRO  one qeastion Can Build New Generator?

**Comment by NycuRO** [comment]
@caspervanneck Yes, but in new branch.

**Comment by caspervanneck** [comment]
why te fuck is it not working @NycuRO get very anry

**Pull request merged**
